# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Waples was here
email: jamwaffles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of web developer and hobbyist engineer James Waples
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://jamwaffles.co.uk" # the base hostname & protocol for your site
twitter_username: Jam_Waffles
github_username:  jamwaffles

# Build settings
markdown: kramdown

kramdown:
  input: GFM