# Site settings
title: James Waples' Internet Hole
logo: logo.png
email: jamwaffles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of web developer and hobby machinist James Waples. He resides in The United Britain and just loves all the rain.
url: "http://wapl.es" # the base hostname & protocol for your site
# baseurl: /blog # the subpath of your site, e.g. /blog/
twitter_username: jam_waffles
github_username:  jamwaffles

# Build settings
markdown: kramdown

kramdown:
  input: GFM